apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-delivery-deployment
spec:
  selector:
    matchLabels:
      app: pizza-delivery-service
  template:
    metadata:
      annotations:  
        dapr.io/app-id: delivery-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
      labels:
        app: pizza-delivery-service
        app.kubernetes.io/name: pizza-delivery-service
        app.kubernetes.io/part-of: pizza-delivery-service
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - name: pizza-delivery-service
        image: salaboy/pizza-delivery:0.1.0
        imagePullPolicy: Always
        env:
        - name: DAPR_HTTP_ENDPOINT
          value: <ADD DAPR_HTTP_ENDPOINT>
        - name: DAPR_GRPC_ENDPOINT
          value: <ADD DAPR_GRPC_ENDPOINT>
        - name: DAPR_API_TOKEN
          value: <ADD DAPR_API_TOKEN>
        - name: JAVA_OPTS
          value: "-XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=75 -XX:TieredStopAtLevel=1"
        - name: PUB_SUB_NAME
          value: pubsub     
        - name: PUB_SUB_NAME
          value: pubsub       
        - name: PUB_SUB_TOPIC
          value: topic    
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pizza-delivery
spec:
  selector:
    app: pizza-delivery-service
  ports:
  - port: 80
    targetPort: 8080             